#!/usr/bin/env python

# Universal constants used in calculations
k = 1.38064852e-23 # m2 kg s-2 K-1
R = 8.3144598 # J K-1 mol-1
Na = 6.02214086e23 # mol-1
h = 6.62607004e-34 # m2 kg s-1
au = 1.660539040e-27 # kg / amu
mass_e = 9.10938356e-31 # kg
atonm = 0.1
nmtom = 1e-9 # m / nm
patobar= 1e-5
K_to_kJmol = k*Na/1000

# Default mdp options for em, npt, nvt, nve etc.
MDP_EM = {
    "integrator"                  :   "steep",
    "nsteps"                      :   50000,
    "init-step"                   :   0,
    "emtol"                       :   20.0,
    "emstep"                      :   0.01,
    "nstxout"                     :   1000,
    "nstvout"                     :   1000,
    "nstenergy"                   :   1000,
    "nstlog"                      :   1000,
    "nstcomm"                     :   1000,
    "energygrps"                  :   None,
    "energygrp-table"             :   None,
    "continuation"                :   "no",
    "constraint-algorithm"        :   "lincs",
    "constraints"                 :   "none",
    "lincs-iter"                  :   3,
    "lincs-order"                 :   4,
    "cutoff-scheme"               :   "Group",
    "ns-type"                     :   "grid",
    "nstlist"                     :   10,
    "rcoulomb"                    :   2,
    "rlist"                       :   2,
    "coulombtype"                 :   "cut-off",
    "epsilon-r"                   :   1,
    "vdwtype"                    :   "user",
    "rvdw"                        :   2,
    "fourierspacing"              :   0.12,
    "fourier-nx"                  :   0,
    "fourier-ny"                  :   0,
    "fourier-nz"                  :   0,
    "pme-order"                   :   4,
    "ewald-rtol"                  :   1e-05,
    "DispCorr"                    :   "no",
    "tcoupl"                      :   "no",
    "pcoupl"                      :   "no",
    "pbc"                         :   "xyz",
    "annealing"                   :   "no",
    "gen-vel"                     :   "yes",
    "gen-temp"                    :   300,
    "gen-seed"                    :   -1,
}

MDP_NVE = {
    "integrator"                  :   "md",
    "tinit"                       :   0,
    "dt"                          :   0.002,
    "nsteps"                      :   2000000,
    "nstxout"                     :   1000,
    "nstvout"                     :   1000,
    "nstfout"                     :   1000,
    "nstcalcenergy"               :   1,
    "nstenergy"                   :   1,
    "nstlog"                      :   1000,
    "nstxtcout"                   :   1000,
    "xtc-precision"               :   1000,
    "comm-mode"                   :   "Linear",
    "nstcomm"                     :   1,
    "energygrps"                  :   None,
    "energygrp-table"             :   None,
    "continuation"                :   "no",
    "constraint-algorithm"        :   "lincs",
    "constraints"                 :   "none",
    "lincs-iter"                  :   3,
    "lincs-order"                 :   4,
    "cutoff-scheme"               :   "Group",
    "ns-type"                     :   "grid",
    "nstlist"                     :   10,
    "rcoulomb"                    :   2,
    "rlist"                       :   2,
    "coulombtype"                 :   "cut-off",
    "epsilon-r"                   :   1,
    "vdwtype"                    :   "user",
    "rvdw"                        :   2,
    "fourierspacing"              :   0.12,
    "fourier-nx"                  :   0,
    "fourier-ny"                  :   0,
    "fourier-nz"                  :   0,
    "pme-order"                   :   4,
    "ewald-rtol"                  :   1e-05,
    "DispCorr"                    :   "no",
    "tcoupl"                      :   "no",
    "pcoupl"                      :   "no",
    "pbc"                         :   "xyz",
    "annealing"                   :   "no",
    "gen-vel"                     :   "no",
}

MDP_NPT = {
    "integrator"                  :   "md",
    "tinit"                       :   0,
    "dt"                          :   0.01,
    "nsteps"                      :   3000000,
    "nstxout"                     :   1000,
    "nstvout"                     :   1000,
    "nstfout"                     :   1000,
    "nstcalcenergy"               :   1000,
    "nstenergy"                   :   1000,
    "nstlog"                      :   1000,
    "nstxtcout"                   :   1000,
    "xtc-precision"               :   1000,
    "comm-mode"                   :   "Linear",
    "nstcomm"                     :   1000,
    "energygrps"                  :   None,
    "energygrp-table"             :   None,
    "continuation"                :   "no",
    "constraint-algorithm"        :   "lincs",
    "constraints"                 :   "none",
    "lincs-iter"                  :   3,
    "lincs-order"                 :   4,
    "cutoff-scheme"               :   "Group",
    "ns-type"                     :   "grid",
    "nstlist"                     :   10,
    "rcoulomb"                    :   2,
    "rlist"                       :   2,
    "coulombtype"                 :   "cut-off",
    "epsilon-r"                   :   1,
    "vdwtype"                    :   "user",
    "rvdw"                        :   2,
    "fourierspacing"              :   0.12,
    "fourier-nx"                  :   0,
    "fourier-ny"                  :   0,
    "fourier-nz"                  :   0,
    "pme-order"                   :   4,
    "ewald-rtol"                  :   1e-05,
    "DispCorr"                    :   "No",
    "tcoupl"                      :   "nose-hoover",
    "tc-grps"                     :   None,
    "tau-t"                       :   2,
    "ref-t"                       :   293.15,
    "pcoupl"                      :   "Parrinello-Rahman",
    "pcoupltype"                  :   "isotropic",
    "tau-p"                       :   2.0,
    "ref-p"                       :   1,
    "compressibility"             :   0.0001,
    "refcoord-scaling"            :   "no",
    "pbc"                         :   "xyz",
    "annealing"                   :   "no",
    "gen-vel"                     :   "no",
}

MDP_NVT = {
    "integrator"                  :   "md",
    "tinit"                       :   0,
    "dt"                          :   0.01,
    "nsteps"                      :   1000000,
    "nstxout"                     :   1000,
    "nstvout"                     :   1000,
    "nstfout"                     :   1000,
    "nstcalcenergy"               :   1000,
    "nstenergy"                   :   1000,
    "nstlog"                      :   1000,
    "nstxtcout"                   :   1000,
    "xtc-precision"               :   1000,
    "comm-mode"                   :   "Linear",
    "nstcomm"                     :   1000,
    "energygrps"                  :   None,
    "energygrp-table"             :   None,
    "continuation"                :   "no",
    "constraint-algorithm"        :   "lincs",
    "constraints"                 :   "none",
    "lincs-iter"                  :   3,
    "lincs-order"                 :   4,
    "cutoff-scheme"               :   "Group",
    "ns-type"                     :   "grid",
    "nstlist"                     :   10,
    "rcoulomb"                    :   2,
    "rlist"                       :   2,
    "coulombtype"                 :   "cut-off",
    "epsilon-r"                   :   1,
    "vdwtype"                    :   "user",
    "rvdw"                        :   2,
    "fourierspacing"              :   0.12,
    "fourier-nx"                  :   0,
    "fourier-ny"                  :   0,
    "fourier-nz"                  :   0,
    "pme-order"                   :   4,
    "ewald-rtol"                  :   1e-05,
    "DispCorr"                    :   "No",
    "tcoupl"                      :   "nose-hoover",
    "tc-grps"                     :   None,
    "tau-t"                       :   2,
    "ref-t"                       :   293.15,
    "pcoupl"                      :   "no",
    "pbc"                         :   "xyz",
    "annealing"                   :   "no",
    "gen-vel"                     :   "no",
}

templates = {"em": MDP_EM, "nve": MDP_NVE, "npt": MDP_NPT, "nvt": MDP_NVT}
# All mdp options extracted with BeautifulSoup from
# https://manual.gromacs.org/documentation/current/user-guide/mdp-options.html
# on 23/04/2021
MDP_OPTIONS = {
    "niter","pull-coord1-geometry","gen-temp","lmc-forced-nstart","tc-grps",
    "table","verlet-buffer-tolerance","electric-field-y","lincs-iter",
    "fourier-ny","ref-t","nh-chain-length","nstxout-compressed","lmc-mc-move",
    "cyl0-down","userint3","userint2","nstlist","init-lambda-weights",
    "rvdw","disre-tau","symmetrized-transition-matrix","nstenergy",
    "pme-order","shake-tol","rot-fit-method0","emtol","constraint-algorithm",
    "pull-coord1-vec","wall-ewald-zfac","nstxout","epsilon-r","coulomb-modifier",
    "bonded-lambdas","orire-tau","awh1-target-beta-scaling",
    "density-guided-simulation-adaptive-force-scaling","integrator",
    "density-guided-simulation-adaptive-force-scaling-time-constant",
    "pull-nstfout","nstcgsteep","bulk-offsetB","pull-print-com","pull-coord1-k",
    "couple-lambda1","massw-split0","awh1-target","rot-pivot0","pull-xout-average",
    "acc-grps","constraints","disre-weighting","wall-density","ewald-rtol-lj",
    "nstexpanded","mts-level2-forces","lmc-repeats","split-group0",
    "nstcalcenergy","rcoulomb","coul-lambdas","deform","energygrps","user2-grps",
    "couple-moltype","epsilon-surface","bulk-offsetA","awh1-error-init",
    "ewald-rtol","nstcomm","awh1-growth","cyl0-r","calc-lambda-neighbors",
    "rlist","rotation","freezedim","rot-group0","density-guided-simulation-force-constant",
    "iontype0-in-B","nstdisreout","awh1-dim1-coord-index","rvdw-switch",
    "rot-nstsout","annealing","mts-levels","cyl1-r","rot-rate0","gen-vel",
    "rot-k0","nwall","rot-potfit-nsteps0","dh-hist-size","awh1-dim1-cover-diameter",
    "ld-seed","rcoulomb-switch","tau-p","pull-print-ref-value","split-group1",
    "solvent-group","temperature-lambdas","pull-coord1-init",
    "density-guided-simulation-similarity-measure","awh1-dim1-diffusion",
    "energygrp-excl","dh-hist-spacing","pull-coord1-dim","cutoff-scheme",
    "swap-frequency","sim-temp-high","orire","nstorireout","pull-ngroups",
    "electric-field-z","nsteps","comm-mode","awh-nsamples-update",
    "orire-fitgrp","pull","orire-fc","compressed-x-grps","iontypes","lj-pme-comb-rule",
    "simulated-tempering","pull-print-components","density-guided-simulation-active",
    "periodic-molecules","annealing-temp","simulated-tempering-scaling",
    "vdw-modifier","mass-lambdas","rot-nstrout","sc-sigma","fep-lambdas",
    "density-guided-simulation-normalize-densities","table-extension",
    "accelerate","awh-seed","awh-nstsample","pcoupl","wl-oneovert","free-energy",
    "pull-coord1-start","density-guided-simulation-atom-spreading-weight",
    "mts-level2-factor","vdwtype","dt","refcoord-scaling","include","rot-potfit-step0",
    "DispCorr","userreal1","define","freezegrps","annealing-time","awh1-dim1-start",
    "lincs-warnangle","rot-slab-dist0","sim-temp-low","init-wl-delta",
    "pull-group1-name","pull-fout-average","dhdl-print-energy","pull-pbc-ref-prev-step-com",
    "awh-potential","init-lambda","massw-split1","lmc-seed","pull-cylinder-r",
    "energygrp-table","awh1-dim1-end","couple-lambda0","density-guided-simulation-group",
    "epsilon-rf","sc-coul","pull-coord1-groups","pull-nstxout","ref-p",
    "nstlog","awh1-target-cutoff","iontype0-name","rot-massw0","pull-coord1-origin",
    "density-guided-simulation-reference-density-filename",
    "morse","cyl0-up","sc-power","fourier-nx","disre-fc","tau-t","disre-mixed",
    "userreal4","restraint-lambdas","density-guided-simulation-shift-vector",
    "pull-coord1-potential-provider","sc-r-power","lmc-stats","simulation-part",
    "wall-r-linpot","pull-group1-weights","vdw-lambdas","nstvout","wall-atomtype",
    "rot-eps0","rot-ngroups","lmc-weights-equil","cos-acceleration",
    "userint4","fcstep","fourier-nz","wl-ratio","pbc","fourierspacing","dhdl-derivatives",
    "awh","nst-transition-matrix","init-step","nstpcouple","userint1",
    "cyl1-up","QMMM","mininum-var-min","userreal2","pcoupltype","lincs-order",
    "nstdhdl","threshold","rot-vec0","pull-ncoords","density-guided-simulation-transformation-matrix",
    "pull-coord1-type","tcoupl","couple-intramol","disre","nsttcouple",
    "awh1-share-group","pull-group1-pbcatom","swapcoords","awh1-dim1-coord-provider",
    "pull-coord1-kB","awh-nbias","awh1-ndim","iontype0-in-A","pull-coord1-rate",
    "comm-grps","userreal3","coulombtype","annealing-npoints","rot-min-gauss0",
    "sc-alpha","print-nose-hoover-chain-variables","user1-grps",
    "mc-temperature","compressibility","nstfout","init-lambda-state",
    "density-guided-simulation-gaussian-transform-spreading-width",
    "awh1-dim1-force-constant","continuation","gen-seed","density-guided-simulation-nst",
    "mts","delta-lambda","awh-nstout","separate-dhdl-file","emstep","awh-share-multisim",
    "tinit","coupl-steps","awh1-equilibrate-histogram","bd-fric","cyl1-down",
    "expanded","density-guided-simulation-gaussian-transform-spreading-range-in-multiples-of-width",
    "nbfgscorr","electric-field-x","rot-type0","QMMM-grps","awh1-user-data",
    "rtpi","wall-type","compressed-x-precision","pull-constr-tol","lmc-gibbsdelta",
    "ewald-geometry","wl-scale",'SH','QMmethod','QMbasis','QMmult','ns-type',
    'CASorbitals','QMMMscheme','CASelectrons','QMcharge'
}
